### ISSUE TITLE
Création de la branche "Develop"

### ISSUE THREAD

**Issue by tijaniabdellatif** [Anassifi/Website-Redesign#1]
# Création de la branche develop 

==> cette branche contiendra tous vos developement 

==> je m'en occupe du merge 

je vous nomme tous @Anassifi @fatimaezzahrazahid1997 @lasridouae @BOUKRIM 

@ Bon courage

**Comment by Fatima-Ezzahra-Zahid** [comment]
j'ai créer la branche
