### ISSUE TITLE
Ma partie de design 

### ISSUE THREAD

**Issue by Anassifi** [Anassifi/Website-Redesign#12]
Je suis entrain de faire ma partie design

**Comment by Anassifi** [comment]
Verifier le pull request #12 @fatimaezzahrazahid1997 @lasridouae @BOUKRIM @salmasan @tijaniabdellatif

**Comment by Fatima-Ezzahra-Zahid** [comment]
@Anassifi  doit ajouter la partier de @salmasa avant vous partie

**Comment by Anassifi** [comment]
> @Anassifi doit ajouter la partier de @salmaSA avant vous partie

tqt c'est justement pour la verification et pour pas perdre le temps en attendant ça partie

**Comment by Fatima-Ezzahra-Zahid** [comment]
merci our votre travail ja valide
