### ISSUE TITLE
ma tache 

### ISSUE THREAD

**Issue by salmasan** [Anassifi/Website-Redesign#14]
j'ai fini mon tache vérifier s'il vous plait #13

**Comment by Anassifi** [comment]
Bonne travail il y'a des changement a faire s'il te plait 
- Photo 2 border encore 6px enlever le
- si vous pouvez centraliser le titre avec la petit shape en bas 
- changez Lvisiter le projet supprimer la "L"
- et changer le text version bold
- minimser la taille du boutton visiter le projet
- Ajouter la version bold du text sur la bar "besoin d'un devis ?"

**Comment by salmasan** [comment]
j'ai modifier tout ce qui à ete dit

**Comment by Fatima-Ezzahra-Zahid** [comment]
j'ai confirme votre modification
