### ISSUE TITLE
Merge des taches des membres 

### ISSUE THREAD

**Issue by Anassifi** [Anassifi/Website-Redesign#17]
Merge des partie des membre en un seul fichier preview 01 @salmasan @fatimaezzahrazahid1997 @Anassifi en attendant les autres merci de verifier

pour @lasridouae @BOUKRIM s'il vous plait finiser le travail avant 3h ou bien en va passez en plan B

**Comment by Fatima-Ezzahra-Zahid** [comment]
j'ai fini cette partie et prototype
